In [6]:
from numpy import *

In [11]:
#using array -- only 1D array possible
arr = array([1,2,3,4,5.0])

print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4. 5.]


In [15]:
#using linspace --the range is divided into parts
arr = linspace(0,20,7) #start end parts

print(arr)

[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.        ]


In [23]:
#using arange -- the rrange is fr 10 raised to start to end
arr = logspace(1,20,5)

print('%.2f' %arr[0])

10.00


In [26]:
arr = zeros(5)
print(arr)
arr = ones(5, int)
print(arr)

[0. 0. 0. 0. 0.]
[1 1 1 1 1]
